#Password policy
[Policy]
#The password should fulfill at least $RequiredChargroups of the following for character group
RequiredChargroups = 3
#Char group preset in the passwords
CharacterGroup = ["lower","upper","number","nonAlpha"]
#Min passwords length
Lehgth = 9
#Password expiration duration
Expire = 90


[Rules]
#Immlemented transform "Lower": words to lower case,"Upper": to upercase,
#"Title": to title,"Togle": toogle chars in words,  
Transforms = ["Lower","Upper","Title","Togle"]
#Dictonaries to use (we will use english keyboard Months inrussian)
Dictionaries=["Month","MonthRus","Common"]
#We ignore num suffixes if words in dict ends with number      
Suffixes = ["1","!","123"]
#Delimeter betwen year and short year suffixes
Delimeters=["@","$","#"]

[Replace]
s = "$"
a = "@" 
l = "1"
O = "0"



[Month]
January = ["January", "Winter"]
February = ["February", "Winter"]
March = ["March", "Winter", "Spring"]
April = ["April", "Spring"]
May = ["May", "Spring", "Summer"]
June = ["June", "Spring","Summer"]
July = ["July", "Summer"]
August= ["August", "Summer", "Fall", "Autumn"]
September = ["September", "Fall", "Autumn"]
October = ["October", "Fall", "Autumn", "Winter"]
November = ["November", "Fall", "Autumn", "Winter", "Thanksgiving"]
December = ["December", "Winter", "Christmas"]

[MonthRus]
January = ["Январь", "Зима"]
February = ["Февраль", "Зима"]
March = ["Март", "Зима", "Весна"]
April = ["Апрель", "Весна"]
May = ["Май", "Весна", "Лето"]
June = ["Июнь", "Весна", "Лето"]
July = ["Июль", "Лето"]
August= ["Август", "Лето", "Осень"]
September = ["Сентябрь", "Осень", "Лето"]
October = ["Октябрь", "Осень"]
November = ["Ноябрь", "Осень"]
December = ["Декабрь", "Зима"]


[Company]
Names= ["EPAM"]

#Common words
[Common]
Words = [
        "Password","123456","123456789","picture","111111","123123",
        "12345","1234567890","senha","1234567","qwerty","abc123","Million2",
        "000000","1234","iloveyou","aaron431","qqww1122",
        "omgpop","123321","654321","qwertyuiop","qwer123456","123456a",
        "a123456","666666","asdfghjkl","ashley","987654321","unknown",
        "zxcvbnm","112233","20100728","123123123","princess","jacket025",
        "evite","123abc","123qwe","sunshine","121212","dragon","1q2w3e4r",
        "5201314","159753","0123456789","pokemon","qwerty","Bangbang",
        "jobandtalent","monkey","1qaz2wsx","abcd1234","default","aaaaaa",
        "soccer","123654","ohmnamah23","12345678910","zing","shadow","102030",
        "11111111","asdfgh","147258369","qazwsx","qwe123","michael","football",
        "baseball","1q2w3e4r5t","party","daniel","asdasd","222222","asd123",
        "555555","a123456789","888888","7777777","fuckyou","1234qwer","superman",
        "147258","999999","159357","love123","tigger","purple","samantha",
        "charlie","babygirl","88888888","jordan23","789456123","jordan","anhyeuem",
        "killer","basketball","michelle","1q2w3e","lol123","789456",
        "6655321","nicole","naruto","master","chocolate","maggie","computer",
        "hannah","jessica","123456789a","hunter","686584","987654321","justin",
        "cookie","hello","blink","andrew","25251325","love","987654","bailey",
        "0123456","101010","12341234","a801016","1111111","anthony","yugioh",
        "amanda","asdf1234","trustno","butterfly","x4ivygA51F","batman",
        "starwars","00000000","lovely","jakcgt333","buster","jennifer","babygirl",
        "family","456789","azerty","andrea","q1w2e3r4","qwer1234","10203","matthew",
        "pepper","12345a","letmein","joshua","131313","123456b","madison",
        "Sample","777777","jesus","taylor","b123456","whatever","welcome",
        "ginger","flower","333333","1111111111","robert","samsung","a12345",
        "loveme","gabriel","alexander","cheese","passw0rd","142536","peanut",
        "11223344","thomas","angel"]
         



